### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by dandarm** [heliphix/btc_data#10]
Hello,

I have a question regarding jupyter notebooks, for example "Training_LSTM_cls.ipynb",
there are read functions called on files not present in repository (for instance "pca_75_clas.csv"),
is there a way to obtain them by running other part of code?

Thanks

**Comment by heliphix** [comment]
Hi,
"pca_75_clas.csv" was generated using the attached code. Please check. Also, you may  check the commit [b80f8913e0](https://github.com/heliphix/btc_data/tree/b80f8913e0) for some selected datasets.

[PCA.zip](https://github.com/heliphix/btc_data/files/7025370/PCA.zip)
