### ISSUE TITLE
Fix for datacollector.py

### ISSUE THREAD

**Issue by jcfbeardsley** [heliphix/btc_data#6]
Hi,

I found your manuscript for this repository to be really interesting - thanks for publishing! I'm now trying to independently recreate the results to better understand how LSTM and Keras work within Python. 

It appears that a small fix for datacollector.py is required for scraping from bitinfocharts.com due to changes on the remote side. Line 100 should now be `values=soup.find_all('script')[4].string` when using Python 3.8 and BS4 >=4.9.3.

Thanks,
J.

**Comment by heliphix** [comment]
Thanks for reporting the error. The code has been updated.
