### ISSUE TITLE
'commons' package missing?

### ISSUE THREAD

**Issue by jcfbeardsley** [heliphix/btc_data#8]
Hi,

Within the feature selection and training notebooks, the import statements specifically reference a `commons` package or file which doesn't appear to be available within the repo:

`import commons as cmns`

A quick search through the `pip`and `conda` libraries suggests this is a custom package - can you please clarify and supply if available?

Thanks in advance.

**Comment by heliphix** [comment]
Hi,
The requested [commons.py](https://raw.githubusercontent.com/heliphix/btc_data/main/commons.py) file is added to the repo.
